# 部署靜態內容到 GitHub Pages 的簡單工作流程
name: Deploy static content to Pages

on:
  # 當推送到預設分支時觸發
  push:
    branches: ["main"]

  # 允許從 Actions 標籤手動運行此工作流程
  workflow_dispatch:

# 設置 GITHUB_TOKEN 的權限以允許部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 允許同時僅有一個部署，跳過在進行中的運行和最新排隊之間的運行。
# 但是，不要取消正在進行的運行，因為我們希望允許這些生產部署完成。
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v3
      - name: 設置 Pages
        uses: actions/configure-pages@v3
      - name: 上傳 artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
