# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Trigger deployment on pushes to the default branch
  push:
    branches: ["main"]

  # Allow manual trigger from the Actions tab
  workflow_dispatch:

# Set permissions for the GITHUB_TOKEN to allow deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up GitHub Pages environment
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # Step 3: Upload static files
      - name: Upload site content
        uses: actions/upload-pages-artifact@v4
        with:
          # Set path to the root folder or correct subfolder containing your site
          path: '.'

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
